### ISSUE TITLE
Update Build?

### ISSUE THREAD

**Issue by fdncred** [cesarsouza/statistics-workbench#2]
Any chance on getting this updated to the latest build of Accord.Net? I think I have most of the code updated but I have these Fody errors.

```
    1>\statistics-workbench-master\packages\Fody.2.1.0\build\netstandard1.0\Fody.targets(57,11): error MSB4064: The "NuGetPackageRoot" parameter is not supported by the "Fody.WeavingTask" task. Verify the parameter exists on the task, and it is a settable public instance property.
    1>\statistics-workbench-master\packages\Fody.2.1.0\build\netstandard1.0\Fody.targets(53,5): error MSB4063: The "Fody.WeavingTask" task could not be initialized with its input parameters. 
```
If I remove the items in the Fody.targets that Fody objects to, I eventually get to this error.
```
    1>MSBUILD : error : Fody: An unhandled exception occurred:
    1>MSBUILD : error : Exception:
    1>MSBUILD : error : Could not load file or assembly 'Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
    1>MSBUILD : error : StackTrace:
    1>MSBUILD : error : 
    1>MSBUILD : error : Server stack trace: 
    1>MSBUILD : error :    at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
    1>MSBUILD : error :    at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
    1>MSBUILD : error :    at System.Reflection.RuntimeMethodInfo.GetParameters()
    1>MSBUILD : error :    at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
    1>MSBUILD : error : 
    1>MSBUILD : error : Exception rethrown at [0]: 
    1>MSBUILD : error :    at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
    1>MSBUILD : error :    at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
    1>MSBUILD : error :    at IInnerWeaver.set_Logger(ILogger value)
    1>MSBUILD : error :    at Processor.ExecuteInOwnAppDomain() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\Fody\Processor.cs:line 146
    1>MSBUILD : error :    at Processor.Inner() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\Fody\Processor.cs:line 93
    1>MSBUILD : error :    at Processor.Execute() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\Fody\Processor.cs:line 45
    1>MSBUILD : error : Source:
    1>MSBUILD : error : mscorlib
    1>MSBUILD : error : TargetSite:
    1>MSBUILD : error : Void GetSignature(Void*, Int32, System.RuntimeFieldHandleInternal, System.IRuntimeMethodInfo, System.RuntimeType)
    1>MSBUILD : error : Could not load file or assembly 'Microsoft.Build.Framework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
    1>MSBUILD : error : StackTrace:
    1>MSBUILD : error : 
    1>MSBUILD : error : 
    1>      Finished Fody 121ms.
```

**Comment by fdncred** [comment]
Nevermind. I got it to work once I manually removed Fody.1.x.xx from the csproj file, after loading the newest Fody. Must be a bug in VS2017. I've seen it leave things behind in the csproj several times.

**Comment by cesarsouza** [comment]
Hi there,

I will leave it open until I actually update it to the latest version. Thanks for opening this issue!

Regards,
Cesar

**Comment by cesarsouza** [comment]
Hi there,

I've just upgraded it to the latest Accord.NET version, VS2017, and .NET 4.6.2.

Regards,
Cesar
